### ISSUE TITLE
Package 'REQUIRES', required by 'emuframework', not found

### ISSUE THREAD

**Issue by palla89** [Rakashazi/emu-ex-plus-alpha#103]
Hi,

I followed @thededman instructions to compile with XCode for iOS (thank you very much!!!) but I'm stuck at the step 5: building the emulators.

All other steps went good with no errors. But when I launch the command `make -f ios-release.mk V=1 -j4` this is the log: 

`MacBook-Pro-di-Alberto-2:NEO.emu alberto$ make -f ios-release.mk V=1 -j4
Building ARMv7 Executable
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f /users/alberto/Desktop/emu-ex-plus-alpha/imagine/make/shortcut/common-builds/ios-armv7.mk O_RELEASE=1 LTO_MODE=lto targetDir=target/ios-release/bin targetFile=neoemu-armv7 buildName=ios-release-armv7  projectPath=.
**Package REQUIRES was not found in the pkg-config search path.
Perhaps you should add the directory containing `REQUIRES.pc'**
to the PKG_CONFIG_PATH environment variable
Package 'REQUIRES', required by 'emuframework', not found
Package REQUIRES was not found in the pkg-config search path.
Perhaps you should add the directory containing `REQUIRES.pc'
to the PKG_CONFIG_PATH environment variable
Package 'REQUIRES', required by 'emuframework', not found
Package REQUIRES was not found in the pkg-config search path.
Perhaps you should add the directory containing `REQUIRES.pc'
to the PKG_CONFIG_PATH environment variable
Package 'REQUIRES', required by 'emuframework', not found
Package REQUIRES was not found in the pkg-config search path.
Perhaps you should add the directory containing `REQUIRES.pc'
to the PKG_CONFIG_PATH environment variable
Package 'REQUIRES', required by 'emuframework', not found
Compiling ./src/main/Main.cc
Compiling ./src/main/unzip.cc
Compiling ./src/main/input.cc
Compiling ./src/main/options.cc
clang -c -MMD -MP ./src/main/Main.cc -DNDEBUG -DNS_BLOCK_ASSERTIONS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=6.0 -arch armv7 -Ibuild/ios-release-armv7/gen -I./src -DHAVE_CONFIG_H  -std=gnu++1z -fno-rtti -fno-exceptions -fno-threadsafe-statics -stdlib=libc++  -pipe -fvisibility=hidden -O3 -fomit-frame-pointer -fno-stack-protector  -flto -mdynamic-no-pic -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -Woverloaded-virtual -o build/ios-release-armv7/obj/main/Main.o
clang -c -MMD -MP ./src/main/unzip.cc -DNDEBUG -DNS_BLOCK_ASSERTIONS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=6.0 -arch armv7 -Ibuild/ios-release-armv7/gen -I./src -DHAVE_CONFIG_H  -std=gnu++1z -fno-rtti -fno-exceptions -fno-threadsafe-statics -stdlib=libc++  -pipe -fvisibility=hidden -O3 -fomit-frame-pointer -fno-stack-protector  -flto -mdynamic-no-pic -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -Woverloaded-virtual -o build/ios-release-armv7/obj/main/unzip.o
clang -c -MMD -MP ./src/main/options.cc -DNDEBUG -DNS_BLOCK_ASSERTIONS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=6.0 -arch armv7 -Ibuild/ios-release-armv7/gen -I./src -DHAVE_CONFIG_H  -std=gnu++1z -fno-rtti -fno-exceptions -fno-threadsafe-statics -stdlib=libc++  -pipe -fvisibility=hidden -O3 -fomit-frame-pointer -fno-stack-protector  -flto -mdynamic-no-pic -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -Woverloaded-virtual -o build/ios-release-armv7/obj/main/options.o
clang -c -MMD -MP ./src/main/input.cc -DNDEBUG -DNS_BLOCK_ASSERTIONS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=6.0 -arch armv7 -Ibuild/ios-release-armv7/gen -I./src -DHAVE_CONFIG_H  -std=gnu++1z -fno-rtti -fno-exceptions -fno-threadsafe-statics -stdlib=libc++  -pipe -fvisibility=hidden -O3 -fomit-frame-pointer -fno-stack-protector  -flto -mdynamic-no-pic -Wall -Wextra -Werror=return-type -Wno-comment -Wno-missing-field-initializers -Wno-unused -Wno-unused-parameter  -Wdisabled-optimization -Wno-attributes -Wno-missing-braces -Woverloaded-virtual -o build/ios-release-armv7/obj/main/input.o
./src/main/Main.cc:17:10: ./src/main/options.cc:fatal error16: :10: 'emuframework/EmuApp.hh' filefatal error : not found
'emuframework/EmuApp.hh' file not
      found
#include <emuframework/EmuApp.hh>
         ^
#include <emuframework/EmuApp.hh>
         ^
./src/main/unzip.cc:17:10: fatal error: 'imagine/fs/ArchiveFS.hh' file not found
#include <imagine/fs/ArchiveFS.hh>
         ^
./src/main/input.cc:16:10: fatal error: 'emuframework/EmuApp.hh' file not found
#include <emuframework/EmuApp.hh>
         ^
1 error generated.
make[1]: *** [build/ios-release-armv7/obj/main/options.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
1 error generated.
make[1]: *** [build/ios-release-armv7/obj/main/input.o] Error 1
make[1]: *** [build/ios-release-armv7/obj/main/Main.o] Error 1
make[1]: *** [build/ios-release-armv7/obj/main/unzip.o] Error 1
make: *** [ios-armv7] Error 2
` 

Can you help me?

**Comment by thededman** [comment]
missed step 4 from my notes. 

Building EmuFramework
In terminal change directory to emu-ex-plus-alpha\EmuFramework

make -f ios-release.mk V=1 -j4 *run this a few time to ensure no errors. *Again I need to running from a Virtual Mac OS X. May not happen on real mac.

This build the emuframework and install in the IMAGINE-SDK folder.

fair warning, it will build fine and emulator will build but you will not able to load ROMS. This has been an issue since last year.

**Comment by palla89** [comment]
Thank you very much @thededman ! I'll try again tomorrow. Yes I love all these emulators, I'm a fan since the first versions. Is he going to mantain the project and fix this problems? I tried to contact him by email without any success :( 

The real reason I would like to build these is because I wanted to make a try porting it also from iOS to tvOS. I asked him if he had any plans but again no answer unfortunately.

Do you know if the last working version works on iOS 11? I tried with the 1.5.29 version IPA i found somewhere, but on iOS 11 I can't install because it was the 32 bit version.

@Rakashazi we need you!! 💟

**Comment by thededman** [comment]
Dang! Total forgot ios11 killed 32bit.
Hmm, I wish I knew how to update the code. I will mess around the next few nights until my foot surgery. i will reply back if I get any where. It will be on my fork.



Sent from my iPhone

On Sep 25, 2017, at 6:58 PM, palla89 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much @thededman<https://github.com/thededman> ! I'll try again tomorrow. Yes I love all these emulators, I'm a fan since the first versions. Is he going to mantain the project and fix this problems? I tried to contact him by email without any success :(

The real reason I would like to build these is because I wanted to make a try porting it also from iOS to tvOS. I asked him if he had any plans but again no answer unfortunately.

Do you know if the last working version works on iOS 11? I tried with the 1.5.29 version IPA i found somewhere, but on iOS 11 I can't install because it was the 32 bit version.

@Rakashazi<https://github.com/rakashazi> we need you!! 💟

**Comment by palla89** [comment]
Good luck for your foot surgery!! Get well soon :) 
Nice, I'll follow your fork and hope to get a new notification here!

**Comment by thededman** [comment]
@palla89 , duh! there is a 64 bit version there! When the emulator compiles the BIN file there is a 32bit version and a ARM64 for 64bit this is the one you need. Be sure to use version this version: Clone this one as this works with file paths **https://github.com/Rakashazi/emu-ex-plus-alpha/tree/8d12806fb939bf57035964c3322f6c714578649c**

Updated my Wiki
https://github.com/thededman/emu-ex-plus-alpha/wiki/emu-ex-plus-alpha-How-to-build-(MacOSX--XCode-Only)

**Comment by palla89** [comment]
You're the best! I'll try it tonight :D 
How is it running on iOS 11?

**Comment by thededman** [comment]
ok, yes it will run and runs fine! 👍 Tested with NES, SNES, NEO, and Sega. Now this was an old build from my saved Xcode builds.
So, cleaned out my imagine-sdk and pull down the older version. Compiled imagine and installed.
TRIED to compile Emuframework, and of course failed. 👎 
Maybe a result of the newer Xcode and iOS 11 rules. I will google this and see if I can't figure it out. 
We may have to wait for @Rakashazi or other coder to help. 
errror:

./src/FileUtils.cc:40:12: error: call to unavailable function 'system': not
      available on iOS
        int err = system(execPath.data());
                  ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/stdlib.h:195:6: note: 
      candidate function has been explicitly made unavailable
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^

**Comment by palla89** [comment]
Hi @thededman ! Tonight I tried everything again, and solved your same problem with the system function not available! I was able to compile the latest version of NEO.emu and launched it! Still with the infamous problem of the inability to load roms because of the sandbox. Here it is what i did:

in my emu-explus-alpha/EmuFramework/src/FileUtils.cc replace the file like this:

`#include <ftw.h>

int unlink_cb(const char *fpath, const struct stat *sb, int typeflag, struct FTW *ftwbuf)
    {
            int rv = remove(fpath);
    
            if (rv)
                    perror(fpath);
        
                return rv;
        }

void fixFilePermissions(const char *path)
{
	#if defined CONFIG_BASE_IOS
	if(!Base::isSystemApp())
		return;
	// try to fix permissions if using jailbreak environment
	if(FS::access(path, FS::acc::w) == 0)
	{
		logMsg("%s lacks write permission, setting user as owner", path);
	}
	else
		return;

	auto execPath = FS::makePathStringPrintf("%s/fixMobilePermission '%s'", Base::assetPath().data(), path);
	//logMsg("executing %s", execPath);
	//int err = system(execPath.data());
    int err = nftw(execPath.data(), unlink_cb, 64, FTW_DEPTH | FTW_PHYS) == -1;
	if(err)
	{
		logWarn("error from fixMobilePermission helper: %d", err);
	}
	#endif
}`

It will work! I tried to solve the problem with sandbox but it's more difficult than I thought, this project is really big! If we could just have a little help from the author, it would be amazing :)

**Comment by thededman** [comment]
@palla89 Thanks. I will look at this change. Dang, I wasn't even close. I was playing with this during my surgery recovery. My mac VM image is damaged so, restoring one from backup, I will try this out on the new and older versions.

**Comment by palla89** [comment]
I solved it by searching on the web if someone else had this problem and found a commit where they were solving it here: https://github.com/cocos2d/cocos2d-x/pull/17921/commits/f45248f2fd80268a59b76e25af673ba96d132517 so don't be sad, it was hard to fix without knowing where to look! :)

**Comment by palla89** [comment]
By the way, I tried to compile the version you linked with file paths working, but it happens the same thing as the latest one to me. Can you check that?

**Comment by palla89** [comment]
[FileUtils.cc.zip](https://github.com/Rakashazi/emu-ex-plus-alpha/files/1360223/FileUtils.cc.zip)

Here it is
