### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by bladeoner** [Rakashazi/emu-ex-plus-alpha#211]
@Rakashazi I hope you are doing fine.

I saw the nightly build was not succesful and tested it on my own machine, I'm getting the same error message not sure what's causing it.

_/tmp/imagine-bundle/libsndfile/libsndfile-1.0.28/src/aiff.c:854:4: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
                        case SFX_MARKER :
                        ^
/tmp/imagine-bundle/libsndfile/libsndfile-1.0.28/src/aiff.c:854:4: note: insert '__attribute__((fallthrough));' to silence this warning
                        case SFX_MARKER :
                        ^
                        __attribute__((fallthrough)); 
/tmp/imagine-bundle/libsndfile/libsndfile-1.0.28/src/aiff.c:854:4: note: insert 'break;' to avoid fall-through
                        case SFX_MARKER :
                        ^
                        break; 
4 warnings and 1 error generated._

**Comment by bladeoner** [comment]
I tried to build with libnsdfile-1.0.31 but I'm getting the same result, thought it might be a bug.

**Comment by Rakashazi** [comment]
Thanks, looks like the recently added -Werror=implicit-fallthrough flag has issues with some of the bundled libraries so I've removed it from the global flags and made it local to Imagine and EmuFramework in the last commit.
